version: "3"

tasks:
  default:
    - task: pre-commit
    - task: migrate

  runserver:
    cmds:
      - poetry run python manage.py runserver

  makemigrations:
    cmds:
      - poetry run python manage.py makemigrations

  migrate:
    cmds:
      - poetry run python manage.py migrate

  pre-commit:
    cmds:
      - poetry run pre-commit install -f --install-hooks

  lintfix:
    cmds:
      - poetry run pre-commit run --all-files
